openapi: 3.0.3
info:
  title: luxor.cloud public API
  version: 0.1.0
paths:
  /:
    get:
      description: Returns metadata about the API.
      responses:
        '200':
          description: API metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  version: 
                    type: string
                    description: version currently available
              example:
                {
                  version: "v1"
                }
  /users/{id}:
    get:
      description: Returns a user based on the given ID.
      parameters:
        - name: id
          in: path
          description: ID of the user to return
          schema: 
            type: string
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
components:
  schemas:
    user:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
