openapi: 3.0.3
info:
  title: luxor.cloud public API
  version: 0.1.0
paths:
  /users/{id}:
    get:
      description: Returns a user based on the given ID.
      parameters:
        - name: id
          in: path
          description: ID of the user to return
          schema: 
            type: string
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User
components:
  schemas:
    User:
      - type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
          name:
            type: string
